version: 2.1

jobs:
  php-codestyle:
    docker:
      - image: mrdollar4444/progect-manager-circleci:latest
    steps:
      - checkout
      - run:
          name: CodeStyle
          command: vendor/bin/phpcs --standard=config/phpcs.xml src import-products-from-gsheet-for-woo-importer.php includes uninstall.php

workflows:
  codestyle:
    jobs:
      - php-codestyle
